version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/apps/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/examples/console-ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/libraries/OmniVoice.Client/src/OmniVoice.Client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/examples/maui/OmniVoiceApi.Maui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/infra/docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
